version: "3.8"

services:
  # ---------- PostgreSQL ----------
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ---------- Сервер (Node.js/Express) ----------
  server:
    build: ./server
    container_name: my_server
    restart: always
    depends_on:
      - postgres
    env_file:
      - ./server/.env
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASS: 123
      DB_NAME: mydatabase
    ports:
      - "3000:3000"

  # ---------- Клиент (React/Vite) ----------
  client:
    build: ./client
    container_name: my_client
    restart: always
    depends_on:
      - server
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev -- --host

volumes:
  postgres_data:
