version: "3.8"

services:
  # ---------- PostgreSQL ----------
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ---------- Сервер (Node.js/Express) ----------
  server:
    build: ./server
    container_name: my_server
    restart: always
    depends_on:
      - postgres
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev

  # ---------- Клиент (React/Vite) ----------
  client:
    build: ./client
    container_name: my_client
    restart: always
    depends_on:
      - server
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev -- --host

volumes:
  postgres_data:
